#pragma once

#include "owo/plugin/plugin_protocol.h"

#include <chrono>
#include <cstdint>
#include <string>
#include <string_view>

namespace owo::plugin {

inline constexpr std::size_t kMaximumPluginWireBytes =
    kMaximumPluginPayloadBytes + 16U * 1024U;

class PluginPipe {
public:
    PluginPipe() = default;
    PluginPipe(const PluginPipe&) = delete;
    PluginPipe& operator=(const PluginPipe&) = delete;
    PluginPipe(PluginPipe&& other) noexcept;
    PluginPipe& operator=(PluginPipe&& other) noexcept;
    ~PluginPipe();

    [[nodiscard]] bool valid() const noexcept;

private:
    PluginPipe(std::uintptr_t native_handle, std::wstring expected_peer_sid,
               bool expected_appcontainer);
    void close() noexcept;

    std::uintptr_t native_handle_{static_cast<std::uintptr_t>(-1)};
    std::wstring expected_peer_sid_;
    bool expected_appcontainer_{};
    std::uint32_t expected_process_id_{};

    friend struct PluginPipeAccess;
    friend struct PluginPipeOpenResult;
    friend PluginPipeOpenResult create_plugin_pipe_server(std::wstring_view);
    friend PluginPipeOpenResult create_full_trust_plugin_pipe_server();
    friend PluginPipeOpenResult connect_plugin_pipe_client(
        std::wstring_view, std::chrono::milliseconds);
    friend struct PluginPipeOperationResult;
    friend PluginPipeOperationResult accept_plugin_pipe_client(
        PluginPipe&, std::chrono::milliseconds);
    friend PluginPipeOperationResult send_plugin_pipe_message(
        PluginPipe&, const PluginMessage&, std::chrono::milliseconds);
    friend struct PluginPipeReceiveResult;
    friend PluginPipeReceiveResult receive_plugin_pipe_message(
        PluginPipe&, std::chrono::milliseconds);
    friend void disconnect_plugin_pipe(PluginPipe&) noexcept;
    friend bool bind_plugin_pipe_client_process(PluginPipe&, std::uint32_t) noexcept;
};

struct PluginPipeOpenResult {
    PluginPipe pipe;
    std::wstring pipe_name;
    std::string diagnostic;

    [[nodiscard]] explicit operator bool() const noexcept {
        return pipe.valid() && diagnostic.empty();
    }
};

struct PluginPipeOperationResult {
    bool ok{};
    std::string diagnostic;
};

struct PluginPipeReceiveResult {
    PluginMessage message;
    PluginPipeOperationResult status;
};

/// Creates one first-instance, single-client LOCAL pipe with an explicit host/AppContainer DACL.
[[nodiscard]] PluginPipeOpenResult create_plugin_pipe_server(
    std::wstring_view expected_appcontainer_sid);

/// Creates a same-session pipe for an explicitly authorized full-trust plugin process.
[[nodiscard]] PluginPipeOpenResult create_full_trust_plugin_pipe_server();

/// Binds the only accepted client to the process created by PluginHost before it is resumed.
[[nodiscard]] bool bind_plugin_pipe_client_process(
    PluginPipe& server, std::uint32_t process_id) noexcept;

/// Connects only to pipe names generated by create_plugin_pipe_server.
[[nodiscard]] PluginPipeOpenResult connect_plugin_pipe_client(
    std::wstring_view pipe_name,
    std::chrono::milliseconds timeout);

[[nodiscard]] PluginPipeOperationResult accept_plugin_pipe_client(
    PluginPipe& server,
    std::chrono::milliseconds timeout);

[[nodiscard]] PluginPipeOperationResult send_plugin_pipe_message(
    PluginPipe& pipe,
    const PluginMessage& message,
    std::chrono::milliseconds timeout);

/// Reads one frame, verifies the connected client's exact AppContainer SID, then decodes OWPH.
[[nodiscard]] PluginPipeReceiveResult receive_plugin_pipe_message(
    PluginPipe& pipe,
    std::chrono::milliseconds timeout);

void disconnect_plugin_pipe(PluginPipe& server) noexcept;

}  // namespace owo::plugin
