[CmdletBinding()]
param(
    [ValidateSet('Debug', 'Release')]
    [string]$Configuration = 'Release',
    [ValidateSet('win-x64')]
    [string]$RuntimeIdentifier = 'win-x64',
    [switch]$NoRestore
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$projectRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$preset = if ($Configuration -eq 'Debug') { 'windows-debug' } else { 'windows-release' }
$configShell = Join-Path $projectRoot "build/$preset/$Configuration/owo_config_shell.exe"
$pluginShell = Join-Path $projectRoot "build/$preset/$Configuration/owo_plugin_shell.exe"
$project = Join-Path $projectRoot 'apps/settings_center/OwO.Settings.csproj'
$platform = 'x64'
$targetFramework = 'net10.0-windows10.0.26100.0'
$buildOutput = Join-Path $projectRoot "apps/settings_center/bin/$platform/$Configuration/$targetFramework/$RuntimeIdentifier"
$publishOutput = Join-Path $projectRoot "build/settings-publish/$RuntimeIdentifier"

cmake --build --preset $preset --target owo_config_shell owo_plugin_shell
if ($LASTEXITCODE -ne 0) { throw "owo_config_shell build failed: $LASTEXITCODE" }

if (-not $NoRestore) {
    dotnet restore $project -r $RuntimeIdentifier --locked-mode
    if ($LASTEXITCODE -ne 0) { throw "settings restore failed: $LASTEXITCODE" }
}

dotnet build $project -c $Configuration -r $RuntimeIdentifier --no-restore `
    "-p:Platform=$platform" `
    "-p:OwOConfigShellPath=$configShell" "-p:OwOPluginShellPath=$pluginShell"
if ($LASTEXITCODE -ne 0) { throw "settings build failed: $LASTEXITCODE" }

$publishRoot = [IO.Path]::GetFullPath((Join-Path $projectRoot 'build/settings-publish'))
$publishOutput = [IO.Path]::GetFullPath($publishOutput)
if (-not $publishOutput.StartsWith($publishRoot + [IO.Path]::DirectorySeparatorChar,
                                   [StringComparison]::OrdinalIgnoreCase)) {
    throw 'Invalid settings publish path.'
}
if (Test-Path -LiteralPath $publishOutput) {
    Remove-Item -LiteralPath $publishOutput -Recurse -Force
}

dotnet publish $project -c $Configuration -r $RuntimeIdentifier --no-restore `
    --self-contained true -o $publishOutput `
    "-p:Platform=$platform" "-p:WindowsAppSDKSelfContained=true" `
    "-p:OwOConfigShellPath=$configShell" "-p:OwOPluginShellPath=$pluginShell"
if ($LASTEXITCODE -ne 0) { throw "settings publish failed: $LASTEXITCODE" }

# The current Windows App SDK publish target omits the app's generated XAML/PRI
# payload even though it copies the WinUI runtime. Without these files the EXE
# fails before showing a window (Microsoft.UI.Xaml.dll, 0xc000027b). Copy only
# the application resources generated by the immediately preceding build.
foreach ($name in @('App.xbf', 'MainPage.xbf', 'MainWindow.xbf', 'OwO.Settings.pri')) {
    Copy-Item -LiteralPath (Join-Path $buildOutput $name) -Destination $publishOutput -Force
}
Copy-Item -LiteralPath (Join-Path $buildOutput 'Assets') -Destination $publishOutput `
    -Recurse -Force

$required = @('OwO.Settings.exe', 'OwO.Settings.dll', 'owo_config_shell.exe',
              'owo_plugin_shell.exe', 'App.xbf', 'MainPage.xbf', 'MainWindow.xbf',
              'OwO.Settings.pri', 'Assets/AppIcon.ico')
foreach ($name in $required) {
    if (-not (Test-Path -LiteralPath (Join-Path $publishOutput $name) -PathType Leaf)) {
        throw "settings output missing: $name"
    }
}
$forbidden = @(Get-ChildItem -LiteralPath $publishOutput -File | Where-Object {
    $_.Name -match '(^|\.)AI\.|MachineLearning|OnnxRuntime|Widgets'
})
if ($forbidden.Count -ne 0) {
    throw "settings output contains unused SDK components: $($forbidden.Name -join ', ')"
}

$sizeMiB = [math]::Round(((Get-ChildItem -LiteralPath $publishOutput -File -Recurse |
    Measure-Object -Property Length -Sum).Sum / 1MB), 2)
Write-Output "OwO settings center ready: $publishOutput"
Write-Output "Published payload: $sizeMiB MiB"
